#!/usr/bin/env bash
# Pre-commit hook
# Place into `.git/hooks` or use `git config core.hooksPath scripts/git-hooks`
# from the root of the repository

set -e

(cd runtime; make build)
git add runtime/dist/runtime.js
cargo test --all
cargo clippy --all -- -Dwarnings
cargo fmt --all --check
./scripts/check_examples_index.sh
(cd web; make lint)
