[package]
name = "lsp-server"

# Inherited from workspace Cargo.toml
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true

[dependencies]
# lsp
lsp = { version = "0.93", package = "lsp-types" }
tower-lsp = { version = "0.17", default-features = false, features = ["runtime-agnostic"] }
# asynchronous locks
async-lock = "2"
# source code spans
codespan = { workspace = true }
# fancy error messages
miette = { workspace = true }
# workspace members
syntax = { path = "../syntax" }
query = { path = "../query" }
printer = { path = "../printer" }
miette_util = { path = "../miette_util" }
