[package]
name = "lsp-server"

# Inherited from workspace Cargo.toml
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true

[dependencies]
# lsp
lsp = { version = "0.93", package = "lsp-types" }
tower-lsp = { version = "0.17", default-features = false, features = ["runtime-agnostic"] }
# asynchronous locks
async-lock = "2"
# source code spans
codespan = { git = "https://github.com/polarity-lang/codespan.git", rev = "542320ab177fd38fff3a398a97b3f0352e065149"}
# fancy error messages
miette = "5"
# workspace members
syntax = { path = "../syntax" }
query = { path = "../query" }
printer = { path = "../printer" }
miette_util = { path = "../miette_util" }
